interface IsymbolMap {
  [key: string]: string;
}

export const SymbolMap: IsymbolMap = {
  'ATM/Cash Machine': 'atm',
  'Accessible Rooms': 'wheelchair-accessible',
  'Accessible Sites': 'wheelchair-accessible',
  'Airboat Launch': 'airboat',
  Amphitheater: 'amphitheater',
  'Animal-Safe Food Storage': 'bear-box',
  'Aquatic Invasive Species Inspection':
    'aquatic-invasive-species-inspection-sticker-black-22',
  'Assistive Listening Systems': 'assistive-listening-systems',
  'Assistive Listening Systems - T-Coil Compatible':
    'assistive-listening-systems-t-coil-compatible',
  'Audio Description': 'audio-description',
  'Audio Description - Live': 'live-audio-description',
  'Automated Entrance': 'automated-entrance',
  'Automated External Defibrillator (AED)': 'aed',
  'Baby Changing Station': 'baby-changing-station',
  'Backcountry Permits': 'backcountry-camping-permit',
  'Beach/Water Access': 'beach-access',
  'Bear Canister Purchase/Rental': 'bear-canister-rentals',
  'Bear Spray Purchase/Rental': 'bear-spray-purchase',
  'Benches/Seating': 'benches-seating',
  'Bicycle - Rack': 'bike-rack',
  'Bicycle - Rental': 'bike-rental',
  'Bicycle - Repair': 'bike-repair',
  'Bicycle - Sharing Station': 'bike-rental',
  'Boat Ramp': 'boat-launch',
  'Boat Rental': 'rentals',
  Braille: 'braille',
  'Bus/Shuttle Stop': 'bus-stop',
  'Canoe/Kayak/Small Boat Launch': 'hand-launch-small-boat-launch',
  'Captioned Media': 'closed-captioning',
  'Cellular Signal': 'cellular-signal',
  'Dock/Pier': 'fishing-pier',
  'Electric Car Charging Station': 'electric-car-charging',
  'Electrical Hookup - Boat/RV': 'electrical-hookup',
  'Electrical Outlet/Cell Phone Charging': 'mobile-device-chargin',
  Elevator: 'elevator',
  'Entrance Passes For Sale': 'entrance-station',
  'Entrance Passes for Sale': 'entrance-station',
  'Ferry - Passenger': 'boat-tour',
  'Ferry - Vehicle': 'vehicle-ferry',
  'Fire Extinguisher': 'fire-extinguisher',
  'Fire Pit': 'campfire',
  'Firewood For Sale/Available': 'firewood',
  'First Aid Kit Available': 'first-aid',
  'First Aid/Medical Care Available': 'first-aid',
  'Fish-Cleaning Station': 'fish-cleaning',
  'Fishing Licenses Issued': 'fishing-license',
  'Food/Drink - Bar/Alcohol For Sale': 'alcohol',
  'Food/Drink - Cafeteria': 'food-service',
  'Food/Drink - Coffee': 'coffee',
  'Food/Drink - Ice Cream': 'ice-cream',
  'Food/Drink - Restaurant/Table Service': 'table-service',
  'Food/Drink - Snacks': 'snack-bar',
  'Food/Drink - Vending Machine/Self Service': 'vending-machine',
  'Fuel (Diesel)': 'gasoline-diesel',
  'Fuel (Unleaded)': 'gasoline',
  'Gifts/Souvenirs/Books': 'souvenir-shop',
  Grill: 'grill',
  'Groceries/Convenience Items': 'store',
  'Historical/Interpretive Information/Exhibits': 'interpretive-exhibit',
  'Hitching Post/Corral': 'horseback-riding',
  Ice: 'ice',
  Information: 'information',
  'Information - Maps Available': 'maps',
  'Information - Park Newspaper Available': 'newspaper',
  'Information - Ranger/Staff Member Present': 'ranger-led-events',
  'Information Kiosk/Bulletin Board': 'trailhead-information',
  'Internet/WiFi Available': 'wi-fi',
  'Junior Ranger Activity': 'junior-ranger-program',
  'Junior Ranger Booklet Available': 'bookstore',
  Kennel: 'kennel',
  'Large Print': 'large-print',
  Laundry: 'laundry',
  'Lifejacket Rentals': 'life-jackets',
  'Locker/Storage': 'lockers-storage',
  'Low-Vision Access': 'low-vison-access',
  Mechanic: 'mechanic',
  'Open Captioning': 'open-captioning',
  'Parking - Auto': 'parking',
  'Parking - Boat Trailer': 'boat-trailer-parking',
  'Parking - Bus/RV': 'rv-campground',
  'Permits Issued': 'passes-and-fees',
  'Pet Boarding': 'stable',
  'Pet Waste Disposal': 'litter-receptacle',
  'Pets Allowed': 'pets-off-leash',
  'Picnic Shelter/Pavilion': 'picnic-shelter',
  'Picnic Table': 'picnic-area',
  Playground: 'playground',
  'Primitive Campsites': 'campgsite',
  'Propane For Sale': 'propane',
  'Propane Recycling': 'propone-bottle-recycling',
  'Public Transit': 'tram-tour',
  'Recreational Field': 'open-to-the-public',
  Recycling: 'recycling',
  Restroom: 'restrooms',
  'Restroom - Accessible': 'wheelchair-accessible',
  'Restroom - Family': 'family-restroom',
  'Restroom - Seasonal': 'winter-recreation-area',
  'Scenic View/Photo Spot': 'scenic-viewpoint',
  'Sea Plane Launch': 'sea-plane',
  'Sewage Dump Station - Boat/RV': 'sanitary-disposal-station',
  'Sewer Hookups - Boat/RV': 'sewer-hookup',
  'Shelter/Cabin': 'shelter',
  Showers: 'showers',
  'Sign Language Interpreter': 'sign-language-interpretation',
  'Ski Rental': 'ski-rental',
  'Supplies - Camping/Outdoor': 'supplies',
  'Supplies - Fishing/Boating': 'supplies',
  'Supplies - General': 'supplies',
  'Swimming Pool': 'swimming',
  'Tactile Exhibit': 'tactile-exhibit',
  Telephone: 'telephone',
  'Tent Campsites': 'campground',
  'Text Telephone/TTY': 'text-telephone-service',
  'Theater/Auditorium': 'theater',
  'Ticket Sales': 'ticket-sales',
  'Toilet - Flush': 'flush-toilets',
  'Toilet - Vault/Composting': 'pit-toilet',
  Trailhead: 'trailhead',
  'Trailhead/Hiker Register': 'trailhead-information',
  'Trash Dumpster': 'trash-dumpster',
  'Trash/Litter Receptacles': 'litter-receptacle',
  'Volume-Controlled Telephone': 'volume-controlled-telephone',
  'Water - Bottle-Filling Station': 'bottle-filling-station',
  'Water - Drinking/Potable': 'drinking-water',
  'Water - Hookup - Boat/RV': 'water-hookup',
  'Water - Non-Potable': 'water-hookup',
  'Wheelchair Accessible': 'wheelchair-accessible',
  'Wheelchairs Available': 'wheelchair-accessible',
};
